spring.application.name=atividade-rabbitMQ-carros

# Banco
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:sptech

# RabbitMQ
mq.exchange.carro=carro.exchange
mq.queue.carro=carro.queue
mq.routing-key.carro=carro.criado
mq.routing-key.carro.venda=carro.vendido

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=myuser
spring.rabbitmq.password=mypassword

# Mail (opcional)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=seu_usuario
spring.mail.password=sua_senha
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true